name: Bot

on:
  push:
    branches: [ main ]
    paths-ignore: 'README.md'
  workflow_dispatch:
   
env:
  GitHubMail: ${{ secrets.GitHubMail }}
  GitHubName: ${{ secrets.GitHubName }}
  BTOKEN: ${{ secrets.BotToken }}
  APIID: ${{ secrets.APIID }}
  APIHASH: ${{ secrets.APIHASH }}

jobs:
  debug:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set Git Configs & Secrets
        run: |
          git config --global user.email ${GitHubMail}
          git config --global user.name ${GitHubName}
          git config --global credential.helper store
          echo "https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials

      - name: Prevent man-db crash
        run: |
          sudo apt-get remove -y --purge man-db

          
      - name: Clone The Bot Repository
        continue-on-error: true
        run: |
          git clone https://github.com/tgcallsjs/LemonJamsBot source
          cd source
          sudo apt-get install npm -y
          
      - name: running Bot
        timeout-minutes: 340
        continue-on-error: true
        run: |
          cd source
          touch dummy.env
          echo "BOT_TOKEN=$BTOKEN" >> dummy.env
          echo "API_ID=$APIID" >> dummy.env
          echo "API_HASH=$APIHASH" >> dummy.env
          echo "WEBSOCKET_URL=https://sexyserver.herokuapp.com/" >> dummy.env
          mv dummy.env .env
          npm install
          npm run build 
          npm start 
          
      - name: Loop Workflow
        continue-on-error: true
        run: |
          # ${GITHUB_REPOSITORY} is the repo slug which runs this script
          git clone https://github.com/henloscape/musicbot loop
          cd loop
          echo $(( RANDOM - ( RANDOM % RANDOM ) )) > looper.txt
          git add looper.txt
          git commit -m "Workflow : Loop at $(date -u +%D-%T%P)"
          git push -q https://${{ secrets.GH_TOKEN }}@github.com/henloscape/musicbot 
